steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-image',
        '.',
      ]

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'jajanjalan-api',
        '--image',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-image',
        '--region',
        'asia-southeast2',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

  # Run database migrations
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npx
    env:
     - DATABASE_URL=mysql://root:rahasia123@34.101.122.161:3306/jajanjalandb
    args:
      - 'prisma'
      - 'db'
      - 'push'
      - '--accept-data-loss'